In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("StudentsPerformance.csv")
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [5]:
df.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [10]:
print(df[['math score', 'reading score', 'writing score']].describe())

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [11]:
print(df[['math score', 'reading score', 'writing score']].mean())

math score       66.089
reading score    69.169
writing score    68.054
dtype: float64

In [12]:
print(df[['math score', 'reading score', 'writing score']].median())

math score       66.0
reading score    70.0
writing score    69.0
dtype: float64

In [13]:
print(df[['math score', 'reading score', 'writing score']].std())

math score       15.163080
reading score    14.600192
writing score    15.195657
dtype: float64

In [14]:
print(df[['math score', 'reading score', 'writing score']].max())

math score       100
reading score    100
writing score    100
dtype: int64

In [15]:
print(df[['math score', 'reading score', 'writing score']].min())

math score        0
reading score    17
writing score    10
dtype: int64

In [16]:
grouped=df.groupby('gender')['math score']
summery_stats=grouped.agg(['mean','median','min','max','std'])
print(summery_stats)

             mean  median  min  max        std
gender
female  63.633205    65.0    0  100  15.491453
male    68.728216    69.0   27  100  14.356277

In [17]:
male_scores = df[df['gender'] == 'male']['math score'].tolist()
female_scores = df[df['gender'] == 'female']['math score'].tolist()

In [18]:
print("\nList of Male Math Scores:")
print(male_scores[:10])

List of Male Math Scores:
[47, 76, 40, 64, 58, 40, 78, 88, 46, 66]

In [19]:
print("\nList of Female Math Scores:")
print(female_scores[:10])

List of Female Math Scores:
[72, 69, 90, 71, 88, 38, 65, 50, 69, 18]

In [20]:
iris=pd.read_csv("Iris.csv")

In [21]:
iris.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [22]:
iris.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [23]:
iris["SepalLengthCm"].describe()

count    150.000000
mean       5.843333
std        0.828066
min        4.300000
25%        5.100000
50%        5.800000
75%        6.400000
max        7.900000
Name: SepalLengthCm, dtype: float64

In [24]:
iris["SepalWidthCm"].describe()

count    150.000000
mean       3.054000
std        0.433594
min        2.000000
25%        2.800000
50%        3.000000
75%        3.300000
max        4.400000
Name: SepalWidthCm, dtype: float64

In [25]:
iris.groupby("Species").describe()

                   Id                                                        \
                count   mean       std    min     25%    50%     75%    max
Species
Iris-setosa      50.0   25.5  14.57738    1.0   13.25   25.5   37.75   50.0
Iris-versicolor  50.0   75.5  14.57738   51.0   63.25   75.5   87.75  100.0
Iris-virginica   50.0  125.5  14.57738  101.0  113.25  125.5  137.75  150.0

                SepalLengthCm         ... PetalLengthCm      PetalWidthCm  \
                        count   mean  ...           75%  max        count
Species                               ...
Iris-setosa              50.0  5.006  ...         1.575  1.9         50.0
Iris-versicolor          50.0  5.936  ...         4.600  5.1         50.0
Iris-virginica           50.0  6.588  ...         5.875  6.9         50.0


                  mean       std  min  25%  50%  75%  max
Species
Iris-setosa      0.244  0.107210  0.1  0.2  0.2  0.3  0.6
Iris-versicolor  1.326  0.197753  1.0  1.2  1.3  1.5  1.8
Iris-virginica   2.026  0.274650  1.4  1.8  2.0  2.3  2.5

[3 rows x 40 columns]